### ISSUE TITLE
Hey Gavin

### ISSUE THREAD

**Issue by pmelanson** [OCESS/orbitx#143]
my discord account got hacked and i'm not able to access it. If you want to add my backup account, it's patrick-monitor-2#6465 but for now you may want to kick my moose mower#1755 account so it doesnt phish anyone else.

**Comment by GoombaG** [comment]
Thanks for the heads up. We kicked (banned? whatever discord mods do) the account for now.

**Comment by pmelanson** [comment]
yayyyy thanks

**Comment by pmelanson** [comment]
Hey @GoombaG I got my account back :)
![image](https://user-images.githubusercontent.com/1498589/142347760-65a8cb26-934f-4dfa-9eb9-0f3bbe18ef2d.png)
mayst I be added back to the server
