### ISSUE TITLE
Getting overflow in np.square in get_acc

### ISSUE THREAD

**Issue by pmelanson** [OCESS/orbitx#21]
Solution might be to astype to float64 or object dtype.

**Comment by sh32kim** [comment]
Centre planet on:/Users/Sean/PycharmProjects/cs493/src/physics.py:31: RuntimeWarning: overflow encountered in square
  D2 = np.square(X - X.transpose()) + np.square(Y - Y.transpose())
/Users/Sean/PycharmProjects/cs493/src/physics.py:52: RuntimeWarning: invalid value encountered in multiply
  Y = np.multiply(np.sin(ang), hyp)
/Users/Sean/PycharmProjects/cs493/src/physics.py:45: RuntimeWarning: invalid value encountered in subtract
  Xd = X - X.transpose()
/Users/Sean/PycharmProjects/cs493/src/physics.py:31: RuntimeWarning: invalid value encountered in subtract
  D2 = np.square(X - X.transpose()) + np.square(Y - Y.transpose())
/Users/Sean/PycharmProjects/VPython/venv/lib/python3.7/site-packages/scipy/integrate/_ivp/rk.py:140: RuntimeWarning: invalid value encountered in maximum
  scale = atol + np.maximum(np.abs(y), np.abs(y_new)) * rtol

**Comment by pmelanson** [comment]
Did you close this because you fixed it?

**Comment by pmelanson** [comment]
The error was that the `where=` keyword in np.divide doesn't work. I replaced it with `np.where`. Patch soon.
