### ISSUE TITLE
LastEndRate issue

### ISSUE THREAD

**Issue by xxxyyyqqq12345** [OCESS/orbitx#33]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/projects/orbitx/flight.py in <module>
    250     warnings.filterwarnings('once', category=DeprecationWarning)
    251     warnings.filterwarnings('once', category=ResourceWarning)
--> 252     main()

~/projects/orbitx/flight.py in main()
    231     try:
    232         if args.data_location.scheme == 'file':
--> 233             lead_server_loop(args)
    234         else:
    235             assert args.data_location.scheme == 'mirror'

~/projects/orbitx/flight.py in lead_server_loop(args)
    184             if not args.no_gui:
    185                 gui.draw(state)
--> 186                 gui.rate(common.FRAMERATE)
    187             else:
    188                 time.sleep(common.TICK_TIME)

~/projects/orbitx/orbitx/flight_gui.py in rate(self, framerate)
    265 
    266     def rate(self, framerate):
--> 267         self._vpython.rate(framerate)

~/projects/orbitx/venv/lib/python3.6/site-packages/vpython/vpython.py in __call__(self, N)
    214         self.rval = N
    215         if self.rval < 1: raise ValueError("rate value must be greater than or equal to 1")
--> 216         super(_RateKeeper2, self).__call__(self.rval) ## calls __call__ in rate_control.py
    217 
    218 if sys.version > '3':

~/projects/orbitx/venv/lib/python3.6/site-packages/vpython/rate_control.py in __call__(self, maxRate)
    171             return
    172 
--> 173         dt = calledTime - self.lastEndRate # time spent in user code
    174         nr = self.whenToRender[self.renderIndex]
    175         if self.count == 2 or (self.count == self.lastCount + self.rateCalls):

AttributeError: '_RateKeeper2' object has no attribute 'lastEndRate'

**Comment by pmelanson** [comment]
Haven't seen this issue in a while, closing
